# Generated by Django 5.0.4 on 2024-06-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_description_remove_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='middle_name',
            new_name='MiddleName',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='first_name',
            new_name='firstName',
        ),
    ]
