# Generated by Django 5.0.4 on 2024-06-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_address_item_address_rename_email_item_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='LastName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='firstName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='MiddleName',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Phone',
            new_name='phone',
        ),
    ]
